import {
  Employee,
  Department,
  Position,
  AttendanceRecord,
  LeaveRequest,
  Payslip,
  PerformanceReview,
  JobOpening,
  Candidate,
  Asset,
  Announcement,
  AuditLog,
  CompanySettings,
  NotificationItem,
} from '../types';

export const INITIAL_SETTINGS: CompanySettings = {
  companyName: 'Etex Technologies Inc.',
  taxId: 'ET-984321092',
  currency: 'ETB',
  fiscalYearStart: '01-01',
  payFrequency: 'Monthly',
  standardWorkHours: 8,
  overtimeMultiplier: 1.5,
  annualLeaveDays: 20,
  sickLeaveDays: 10,
  maternityLeaveDays: 90,
  paternityLeaveDays: 14,
  address: '500 Tech Parkway, Suite 400, San Francisco, CA 94107',
  contactEmail: 'hr@etex.com',
  contactPhone: '+1 (415) 890-2300',
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Engineering',
    code: 'ENG',
    managerId: 'EMP-1002',
    managerName: 'Elena Rostova',
    costCenter: 'CC-101',
    location: 'HQ - San Francisco',
    description: 'Product development, infrastructure, AI & software engineering.',
    employeeCount: 6,
  },
  {
    id: 'dept-2',
    name: 'Human Resources',
    code: 'HR',
    managerId: 'EMP-1001',
    managerName: 'Sarah Jenkins',
    costCenter: 'CC-102',
    location: 'HQ - San Francisco',
    description: 'Talent acquisition, employee experience, compliance & payroll.',
    employeeCount: 3,
  },
  {
    id: 'dept-3',
    name: 'Sales & Marketing',
    code: 'SLM',
    managerId: 'EMP-1005',
    managerName: 'Marcus Vance',
    costCenter: 'CC-103',
    location: 'HQ - San Francisco',
    description: 'Enterprise business development, growth, and brand strategy.',
    employeeCount: 4,
  },
  {
    id: 'dept-4',
    name: 'Finance & Accounting',
    code: 'FIN',
    managerId: 'EMP-1008',
    managerName: 'David Chen',
    costCenter: 'CC-104',
    location: 'HQ - San Francisco',
    description: 'Financial planning, reporting, treasury, and audit.',
    employeeCount: 2,
  },
  {
    id: 'dept-5',
    name: 'Product & Design',
    code: 'PRD',
    managerId: 'EMP-1003',
    managerName: 'Alex Thorne',
    costCenter: 'CC-105',
    location: 'Austin Branch',
    description: 'User experience research, UI design, and product lifecycle management.',
    employeeCount: 3,
  },
];

export const INITIAL_POSITIONS: Position[] = [
  { id: 'pos-1', title: 'VP of Engineering', department: 'Engineering', grade: 'E-8', description: 'Leads global engineering team and technology strategy.' },
  { id: 'pos-2', title: 'Senior Software Engineer', department: 'Engineering', grade: 'E-5', description: 'Full-stack application development & cloud architecture.' },
  { id: 'pos-3', title: 'Frontend Developer', department: 'Engineering', grade: 'E-3', description: 'UI component development and performance optimization.' },
  { id: 'pos-4', title: 'HR Director', department: 'Human Resources', grade: 'M-7', description: 'Strategic HR, policy governance, and organizational development.' },
  { id: 'pos-5', title: 'Payroll & Benefits Specialist', department: 'Human Resources', grade: 'M-4', description: 'Monthly payroll calculation, tax filings, and benefits admin.' },
  { id: 'pos-6', title: 'Lead Product Designer', department: 'Product & Design', grade: 'P-5', description: 'Design system architecture and user experience strategy.' },
  { id: 'pos-7', title: 'Sales Manager', department: 'Sales & Marketing', grade: 'S-6', description: 'Enterprise sales pipeline management and client revenue.' },
  { id: 'pos-8', title: 'Senior Financial Analyst', department: 'Finance & Accounting', grade: 'F-5', description: 'FP&A modeling, budget forecasting, and cost audit.' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1001',
    employeeId: 'EMP-1001',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    fullName: 'Sarah Jenkins',
    email: 'sarah.jenkins@apex.com',
    phone: '+1 (415) 555-0192',
    gender: 'Female',
    dateOfBirth: '1988-08-14',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    address: '1428 Elm Street, San Francisco, CA',
    emergencyContact: { name: 'Robert Jenkins', relationship: 'Spouse', phone: '+1 (415) 555-9011' },
    department: 'Human Resources',
    position: 'HR Director',
    employmentType: 'Full-Time',
    hireDate: '2021-03-15',
    employmentStatus: 'Active',
    salary: 145000,
    payType: 'Salary',
    hourlyRate: 69.71,
    payFrequency: 'Monthly',
    costCenter: 'CC-102',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Chase Bank', accountNumber: '****4829', routingNumber: '121000358' },
    taxInfo: { taxId: 'XXX-XX-4819', filingStatus: 'Married Filing Jointly', allowances: 2 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [
      { id: 'doc-1', name: 'Offer_Letter_Jenkins.pdf', type: 'Offer Letter', url: '#', uploadedAt: '2021-03-01' },
      { id: 'doc-2', name: 'Employment_Contract_2021.pdf', type: 'Contract', url: '#', uploadedAt: '2021-03-15' },
    ],
    leaveBalance: { annual: 18, sick: 9, personal: 4, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Primary HR Admin contact.',
    createdAt: '2021-03-15T09:00:00Z',
    updatedAt: '2026-08-01T10:30:00Z',
  },
  {
    id: 'emp-1002',
    employeeId: 'EMP-1002',
    firstName: 'Elena',
    lastName: 'Rostova',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@apex.com',
    phone: '+1 (415) 555-0821',
    gender: 'Female',
    dateOfBirth: '1985-11-22',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    address: '742 Evergreen Terrace, San Francisco, CA',
    emergencyContact: { name: 'Dmitri Rostov', relationship: 'Brother', phone: '+1 (415) 555-2244' },
    department: 'Engineering',
    position: 'VP of Engineering',
    employmentType: 'Full-Time',
    hireDate: '2020-01-10',
    employmentStatus: 'Active',
    salary: 195000,
    payType: 'Salary',
    hourlyRate: 93.75,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Wells Fargo', accountNumber: '****9102', routingNumber: '121000248' },
    taxInfo: { taxId: 'XXX-XX-9012', filingStatus: 'Single', allowances: 1 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [
      { id: 'doc-3', name: 'Contract_Rostova.pdf', type: 'Contract', url: '#', uploadedAt: '2020-01-10' },
    ],
    leaveBalance: { annual: 14, sick: 10, personal: 5, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Department manager for Engineering.',
    createdAt: '2020-01-10T09:00:00Z',
    updatedAt: '2026-08-01T11:00:00Z',
  },
  {
    id: 'emp-1003',
    employeeId: 'EMP-1003',
    firstName: 'Alex',
    lastName: 'Thorne',
    fullName: 'Alex Thorne',
    email: 'alex.thorne@apex.com',
    phone: '+1 (512) 555-3921',
    gender: 'Non-Binary',
    dateOfBirth: '1992-04-18',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    address: '300 Congress Ave, Austin, TX',
    emergencyContact: { name: 'Morgan Thorne', relationship: 'Sibling', phone: '+1 (512) 555-8833' },
    department: 'Product & Design',
    position: 'Lead Product Designer',
    managerId: 'EMP-1002',
    managerName: 'Elena Rostova',
    employmentType: 'Full-Time',
    hireDate: '2022-06-01',
    employmentStatus: 'Active',
    salary: 130000,
    payType: 'Salary',
    hourlyRate: 62.50,
    payFrequency: 'Monthly',
    costCenter: 'CC-105',
    location: 'Austin Branch',
    bankInfo: { bankName: 'Bank of America', accountNumber: '****3391', routingNumber: '111000025' },
    taxInfo: { taxId: 'XXX-XX-3301', filingStatus: 'Single', allowances: 1 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [
      { id: 'doc-4', name: 'Resume_Thorne.pdf', type: 'Resume', url: '#', uploadedAt: '2022-05-15' },
    ],
    leaveBalance: { annual: 12, sick: 8, personal: 3, maternity: 0, paternity: 0, bereavement: 5 },
    notes: 'Leads Austin UI/UX design chapter.',
    createdAt: '2022-06-01T09:00:00Z',
    updatedAt: '2026-08-01T11:15:00Z',
  },
  {
    id: 'emp-1004',
    employeeId: 'EMP-1004',
    firstName: 'Michael',
    lastName: 'Chang',
    fullName: 'Michael Chang',
    email: 'michael.chang@apex.com',
    phone: '+1 (415) 555-7731',
    gender: 'Male',
    dateOfBirth: '1995-08-09', // Birthday coming up this month!
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    address: '88 Market St, San Francisco, CA',
    emergencyContact: { name: 'Linda Chang', relationship: 'Mother', phone: '+1 (415) 555-1099' },
    department: 'Engineering',
    position: 'Senior Software Engineer',
    managerId: 'EMP-1002',
    managerName: 'Elena Rostova',
    employmentType: 'Full-Time',
    hireDate: '2022-08-15', // Work anniversary coming up this month!
    employmentStatus: 'Active',
    salary: 155000,
    payType: 'Salary',
    hourlyRate: 74.52,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'First Republic Bank', accountNumber: '****7712', routingNumber: '121000358' },
    taxInfo: { taxId: 'XXX-XX-7811', filingStatus: 'Single', allowances: 1 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 15, sick: 10, personal: 4, maternity: 0, paternity: 0, bereavement: 5 },
    notes: 'Core contributor on backend infrastructure.',
    createdAt: '2022-08-15T09:00:00Z',
    updatedAt: '2026-08-01T11:20:00Z',
  },
  {
    id: 'emp-1005',
    employeeId: 'EMP-1005',
    firstName: 'Marcus',
    lastName: 'Vance',
    fullName: 'Marcus Vance',
    email: 'marcus.vance@apex.com',
    phone: '+1 (415) 555-8820',
    gender: 'Male',
    dateOfBirth: '1987-12-03',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    address: '501 Mission St, San Francisco, CA',
    emergencyContact: { name: 'Jessica Vance', relationship: 'Spouse', phone: '+1 (415) 555-9922' },
    department: 'Sales & Marketing',
    position: 'Sales Manager',
    employmentType: 'Full-Time',
    hireDate: '2021-09-01',
    employmentStatus: 'Active',
    salary: 135000,
    payType: 'Salary',
    hourlyRate: 64.90,
    payFrequency: 'Monthly',
    costCenter: 'CC-103',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Citibank', accountNumber: '****1182', routingNumber: '021000089' },
    taxInfo: { taxId: 'XXX-XX-1102', filingStatus: 'Married Filing Jointly', allowances: 3 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 16, sick: 7, personal: 2, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Head of West Coast Enterprise sales.',
    createdAt: '2021-09-01T09:00:00Z',
    updatedAt: '2026-08-01T11:30:00Z',
  },
  {
    id: 'emp-1006',
    employeeId: 'EMP-1006',
    firstName: 'Aisha',
    lastName: 'Patel',
    fullName: 'Aisha Patel',
    email: 'aisha.patel@apex.com',
    phone: '+1 (415) 555-3392',
    gender: 'Female',
    dateOfBirth: '1996-08-28', // Birthday coming up this month!
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    address: '101 Post St, San Francisco, CA',
    emergencyContact: { name: 'Sanjay Patel', relationship: 'Father', phone: '+1 (415) 555-4411' },
    department: 'Engineering',
    position: 'Frontend Developer',
    managerId: 'EMP-1002',
    managerName: 'Elena Rostova',
    employmentType: 'Full-Time',
    hireDate: '2024-02-01',
    employmentStatus: 'Active',
    salary: 115000,
    payType: 'Salary',
    hourlyRate: 55.28,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Chase Bank', accountNumber: '****9012', routingNumber: '121000358' },
    taxInfo: { taxId: 'XXX-XX-5521', filingStatus: 'Single', allowances: 1 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 19, sick: 10, personal: 5, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Specializes in React & Tailwind Web Applications.',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2026-08-01T11:40:00Z',
  },
  {
    id: 'emp-1007',
    employeeId: 'EMP-1007',
    firstName: 'James',
    lastName: 'Wilson',
    fullName: 'James Wilson',
    email: 'james.wilson@apex.com',
    phone: '+1 (415) 555-2201',
    gender: 'Male',
    dateOfBirth: '1991-03-14',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    address: '452 Geary Blvd, San Francisco, CA',
    emergencyContact: { name: 'Clara Wilson', relationship: 'Spouse', phone: '+1 (415) 555-3311' },
    department: 'Human Resources',
    position: 'Payroll & Benefits Specialist',
    managerId: 'EMP-1001',
    managerName: 'Sarah Jenkins',
    employmentType: 'Full-Time',
    hireDate: '2023-05-10',
    employmentStatus: 'Active',
    salary: 95000,
    payType: 'Salary',
    hourlyRate: 45.67,
    payFrequency: 'Monthly',
    costCenter: 'CC-102',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Wells Fargo', accountNumber: '****4402', routingNumber: '121000248' },
    taxInfo: { taxId: 'XXX-XX-4491', filingStatus: 'Married Filing Jointly', allowances: 2 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 16, sick: 8, personal: 3, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Payroll Officer role user.',
    createdAt: '2023-05-10T09:00:00Z',
    updatedAt: '2026-08-01T11:45:00Z',
  },
  {
    id: 'emp-1008',
    employeeId: 'EMP-1008',
    firstName: 'David',
    lastName: 'Chen',
    fullName: 'David Chen',
    email: 'david.chen@apex.com',
    phone: '+1 (415) 555-9018',
    gender: 'Male',
    dateOfBirth: '1984-07-30',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    address: '120 Valencia St, San Francisco, CA',
    emergencyContact: { name: 'Grace Chen', relationship: 'Spouse', phone: '+1 (415) 555-0012' },
    department: 'Finance & Accounting',
    position: 'Senior Financial Analyst',
    employmentType: 'Full-Time',
    hireDate: '2020-08-10', // Anniversary this month!
    employmentStatus: 'Active',
    salary: 138000,
    payType: 'Salary',
    hourlyRate: 66.35,
    payFrequency: 'Monthly',
    costCenter: 'CC-104',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Bank of America', accountNumber: '****8831', routingNumber: '111000025' },
    taxInfo: { taxId: 'XXX-XX-8822', filingStatus: 'Married Filing Jointly', allowances: 2 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 15, sick: 9, personal: 4, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Finance department manager.',
    createdAt: '2020-08-10T09:00:00Z',
    updatedAt: '2026-08-01T11:50:00Z',
  },
  {
    id: 'emp-1009',
    employeeId: 'EMP-1009',
    firstName: 'Sophia',
    lastName: 'Martinez',
    fullName: 'Sophia Martinez',
    email: 'sophia.martinez@apex.com',
    phone: '+1 (415) 555-1198',
    gender: 'Female',
    dateOfBirth: '1994-10-12',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    address: '920 Montgomery St, San Francisco, CA',
    emergencyContact: { name: 'Carlos Martinez', relationship: 'Brother', phone: '+1 (415) 555-2288' },
    department: 'Sales & Marketing',
    position: 'Marketing Specialist',
    managerId: 'EMP-1005',
    managerName: 'Marcus Vance',
    employmentType: 'Full-Time',
    hireDate: '2023-11-01',
    employmentStatus: 'On Leave',
    salary: 92000,
    payType: 'Salary',
    hourlyRate: 44.23,
    payFrequency: 'Monthly',
    costCenter: 'CC-103',
    location: 'HQ - San Francisco',
    bankInfo: { bankName: 'Chase Bank', accountNumber: '****5521', routingNumber: '121000358' },
    taxInfo: { taxId: 'XXX-XX-9901', filingStatus: 'Single', allowances: 1 },
    workSchedule: 'Mon - Fri, 9:00 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 10, sick: 6, personal: 2, maternity: 80, paternity: 0, bereavement: 5 },
    notes: 'Currently on Maternity leave.',
    createdAt: '2023-11-01T09:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'EMP-1001',
    employeeName: 'Sarah Jenkins',
    department: 'Human Resources',
    date: '2026-08-05',
    clockIn: '08:52 AM',
    clockOut: '05:05 PM',
    breakDurationMinutes: 45,
    totalHours: 7.5,
    overtimeHours: 0,
    status: 'Present',
  },
  {
    id: 'att-2',
    employeeId: 'EMP-1002',
    employeeName: 'Elena Rostova',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:45 AM',
    clockOut: '05:30 PM',
    breakDurationMinutes: 60,
    totalHours: 7.75,
    overtimeHours: 0.5,
    status: 'Present',
  },
  {
    id: 'att-3',
    employeeId: 'EMP-1003',
    employeeName: 'Alex Thorne',
    department: 'Product & Design',
    date: '2026-08-05',
    clockIn: '09:18 AM',
    clockOut: '05:00 PM',
    breakDurationMinutes: 60,
    totalHours: 6.7,
    overtimeHours: 0,
    status: 'Late',
    notes: 'Traffic delay on Austin highway',
  },
  {
    id: 'att-4',
    employeeId: 'EMP-1004',
    employeeName: 'Michael Chang',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:55 AM',
    clockOut: '06:15 PM',
    breakDurationMinutes: 45,
    totalHours: 8.5,
    overtimeHours: 1.25,
    status: 'Present',
  },
  {
    id: 'att-5',
    employeeId: 'EMP-1006',
    employeeName: 'Aisha Patel',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:50 AM',
    clockOut: '05:00 PM',
    breakDurationMinutes: 60,
    totalHours: 7.1,
    overtimeHours: 0,
    status: 'Present',
  },
  {
    id: 'att-6',
    employeeId: 'EMP-1009',
    employeeName: 'Sophia Martinez',
    department: 'Sales & Marketing',
    date: '2026-08-05',
    breakDurationMinutes: 0,
    totalHours: 0,
    overtimeHours: 0,
    status: 'On Leave',
    notes: 'Approved Maternity Leave',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lv-101',
    employeeId: 'EMP-1004',
    employeeName: 'Michael Chang',
    department: 'Engineering',
    leaveType: 'Annual',
    startDate: '2026-08-18',
    endDate: '2026-08-22',
    totalDays: 5,
    reason: 'Summer family vacation trip.',
    status: 'Pending',
    appliedAt: '2026-08-04T14:20:00Z',
  },
  {
    id: 'lv-102',
    employeeId: 'EMP-1006',
    employeeName: 'Aisha Patel',
    department: 'Engineering',
    leaveType: 'Sick',
    startDate: '2026-08-10',
    endDate: '2026-08-11',
    totalDays: 2,
    reason: 'Dental surgery and recovery.',
    status: 'Pending',
    appliedAt: '2026-08-05T09:10:00Z',
  },
  {
    id: 'lv-103',
    employeeId: 'EMP-1003',
    employeeName: 'Alex Thorne',
    department: 'Product & Design',
    leaveType: 'Personal',
    startDate: '2026-07-28',
    endDate: '2026-07-29',
    totalDays: 2,
    reason: 'Moving to new apartment.',
    status: 'Approved',
    approverId: 'EMP-1002',
    approverName: 'Elena Rostova',
    approverNote: 'Approved. Safe moving!',
    appliedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'lv-104',
    employeeId: 'EMP-1009',
    employeeName: 'Sophia Martinez',
    department: 'Sales & Marketing',
    leaveType: 'Maternity',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    totalDays: 65,
    reason: 'Maternity leave.',
    status: 'Approved',
    approverId: 'EMP-1001',
    approverName: 'Sarah Jenkins',
    approverNote: 'Congratulations on your new baby!',
    appliedAt: '2026-06-15T11:00:00Z',
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-2026-07-1001',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1001',
    employeeName: 'Sarah Jenkins',
    employeeEmail: 'sarah.jenkins@etex.com',
    department: 'Human Resources',
    position: 'HR Director',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 12083.33,
    hourlyRate: 69.71,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 1000,
    commissions: 0,
    allowances: 300,
    grossPay: 13383.33,
    taxDeductions: 2665.00,
    retirementDeductions: 936.83,
    otherDeductions: 150.00,
    totalDeductions: 3751.83,
    netPay: 9631.50,
    paymentMethod: 'Direct Deposit',
    bankName: 'Commercial Bank of Ethiopia',
    accountNumber: '****4829',
    status: 'Completed',
  },
  {
    id: 'ps-2026-07-1002',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1002',
    employeeName: 'Elena Rostova',
    employeeEmail: 'elena.rostova@etex.com',
    department: 'Engineering',
    position: 'VP of Engineering',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 16250.00,
    hourlyRate: 93.75,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 2500,
    commissions: 0,
    allowances: 400,
    grossPay: 19150.00,
    taxDeductions: 4652.50,
    retirementDeductions: 1340.50,
    otherDeductions: 200.00,
    totalDeductions: 6193.00,
    netPay: 12957.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Dashen Bank',
    accountNumber: '****9102',
    status: 'Completed',
  },
  {
    id: 'ps-2026-07-1004',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1004',
    employeeName: 'Michael Chang',
    employeeEmail: 'michael.chang@etex.com',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 12916.67,
    hourlyRate: 74.52,
    hoursWorked: 168,
    overtimePay: 894.24,
    bonuses: 500,
    commissions: 0,
    allowances: 250,
    grossPay: 14560.91,
    taxDeductions: 3046.32,
    retirementDeductions: 1019.26,
    otherDeductions: 120.00,
    totalDeductions: 4185.58,
    netPay: 10375.33,
    paymentMethod: 'Direct Deposit',
    bankName: 'Awash Bank',
    accountNumber: '****7712',
    status: 'Completed',
  },
];

export const INITIAL_PERFORMANCE_REVIEWS: PerformanceReview[] = [
  {
    id: 'rev-1',
    employeeId: 'EMP-1004',
    employeeName: 'Michael Chang',
    reviewerId: 'EMP-1002',
    reviewerName: 'Elena Rostova',
    reviewPeriod: 'Q2 2026',
    overallRating: 4.8,
    goals: [
      { id: 'g1', title: 'Migrate legacy microservices to GraphQL', description: 'Complete backend migration with zero downtime.', status: 'Completed', progress: 100, dueDate: '2026-06-30' },
      { id: 'g2', title: 'Improve test coverage to 85%', description: 'Write unit & integration tests.', status: 'In Progress', progress: 75, dueDate: '2026-09-30' },
    ],
    feedback: 'Michael has demonstrated stellar technical leadership and architectural excellence during the infrastructure upgrade.',
    strengths: 'System design, reliability, team mentoring',
    improvements: 'Technical documentation completeness',
    status: 'Completed',
    reviewDate: '2026-07-05',
  },
  {
    id: 'rev-2',
    employeeId: 'EMP-1006',
    employeeName: 'Aisha Patel',
    reviewerId: 'EMP-1002',
    reviewerName: 'Elena Rostova',
    reviewPeriod: 'Q2 2026',
    overallRating: 4.5,
    goals: [
      { id: 'g3', title: 'Redesign Design System Components', description: 'Build accessible Tailwind UI primitives.', status: 'Completed', progress: 100, dueDate: '2026-06-30' },
    ],
    feedback: 'Aisha delivered exceptional UI components and significantly boosted web application responsiveness.',
    strengths: 'UI Craftsmanship, fast execution, accessibility focus',
    improvements: 'Cross-browser testing protocols',
    status: 'Completed',
    reviewDate: '2026-07-08',
  },
];

export const INITIAL_JOBS: JobOpening[] = [
  {
    id: 'job-1',
    title: 'Senior DevOps / Site Reliability Engineer',
    department: 'Engineering',
    location: 'HQ - San Francisco / Remote',
    employmentType: 'Full-Time',
    status: 'Open',
    applicantsCount: 14,
    description: 'Lead Kubernetes cluster orchestration, Terraform IaC, and CI/CD pipelines.',
    requirements: ['5+ years DevOps/SRE', 'AWS/GCP, Docker, Kubernetes', 'Terraform & GitHub Actions'],
    postedDate: '2026-07-15',
  },
  {
    id: 'job-2',
    title: 'Senior Product Manager',
    department: 'Product & Design',
    location: 'Austin Branch / Remote',
    employmentType: 'Full-Time',
    status: 'Open',
    applicantsCount: 9,
    description: 'Drive product roadmap for SaaS enterprise features and integrations.',
    requirements: ['4+ years B2B SaaS PM', 'Data analytics & user research', 'Agile leadership'],
    postedDate: '2026-07-20',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    jobId: 'job-1',
    jobTitle: 'Senior DevOps / Site Reliability Engineer',
    name: 'Robert Vance',
    email: 'robert.vance@gmail.com',
    phone: '+1 (415) 889-1100',
    status: 'Interview',
    appliedDate: '2026-07-18',
    interviewDate: '2026-08-08 at 2:00 PM',
    notes: 'Passed initial screening call with flying colors. Strong Terraform expertise.',
    rating: 4,
  },
  {
    id: 'cand-2',
    jobId: 'job-1',
    jobTitle: 'Senior DevOps / Site Reliability Engineer',
    name: 'Emily Watson',
    email: 'e.watson@techmail.com',
    phone: '+1 (512) 330-9922',
    status: 'Screening',
    appliedDate: '2026-07-22',
    notes: 'Resume looks solid. Ex-Google Cloud engineer.',
    rating: 5,
  },
  {
    id: 'cand-3',
    jobId: 'job-2',
    jobTitle: 'Senior Product Manager',
    name: 'Daniel Kim',
    email: 'daniel.kim@innovate.io',
    phone: '+1 (415) 771-3344',
    status: 'Offer',
    appliedDate: '2026-07-21',
    notes: 'Final round interview completed. Extended $150k offer letter.',
    rating: 5,
  },
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-1',
    assetTag: 'AST-MBP-101',
    name: 'MacBook Pro 16" M3 Max (32GB / 1TB)',
    category: 'Laptop',
    serialNumber: 'C02G8091Q05P',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1004',
    assignedEmployeeName: 'Michael Chang',
    assignedDate: '2022-08-15',
    value: 3499,
    notes: 'High performance engineer laptop',
  },
  {
    id: 'ast-2',
    assetTag: 'AST-MON-204',
    name: 'Dell UltraSharp 32" 4K USB-C Monitor',
    category: 'Monitor',
    serialNumber: 'CN-09121-770',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1003',
    assignedEmployeeName: 'Alex Thorne',
    assignedDate: '2022-06-05',
    value: 850,
    notes: 'Color calibrated for product design team',
  },
  {
    id: 'ast-3',
    assetTag: 'AST-MBP-102',
    name: 'MacBook Air 15" M3 (16GB / 512GB)',
    category: 'Laptop',
    serialNumber: 'C02H1108P901',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1001',
    assignedEmployeeName: 'Sarah Jenkins',
    assignedDate: '2023-01-10',
    value: 1699,
  },
  {
    id: 'ast-4',
    assetTag: 'AST-ACC-001',
    name: 'HQ Master Keycard & Parking Pass #042',
    category: 'Access Card',
    serialNumber: 'KEY-SF-042',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1002',
    assignedEmployeeName: 'Elena Rostova',
    assignedDate: '2020-01-10',
    value: 50,
  },
  {
    id: 'ast-5',
    assetTag: 'AST-MBP-105',
    name: 'MacBook Pro 14" M3 Pro (18GB / 512GB)',
    category: 'Laptop',
    serialNumber: 'C02F9918A003',
    status: 'Available',
    value: 1999,
    notes: 'Ready for next new hire in Engineering',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Q3 Town Hall & All-Hands Meeting',
    content: 'Join us this Thursday at 10:00 AM PST for our Q3 Company Update. We will share financial performance, product milestones, and welcome new team members.',
    author: 'Sarah Jenkins (HR)',
    category: 'Event',
    isPinned: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'anc-2',
    title: 'Updated Health & Dental Benefits Package for 2026',
    content: 'We are excited to introduce enhanced healthcare coverage including $0 copay mental health consultations and gym stipend increases to $100/mo.',
    author: 'James Wilson (Payroll)',
    category: 'Policy',
    isPinned: false,
    createdAt: '2026-07-25T14:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userName: 'Sarah Jenkins',
    userRole: 'HR Manager',
    action: 'Approved Leave Request',
    module: 'Leave Management',
    details: 'Approved 2 days personal leave for Alex Thorne (EMP-1003)',
    timestamp: '2026-08-04T16:10:00Z',
  },
  {
    id: 'log-2',
    userName: 'James Wilson',
    userRole: 'HR Manager',
    action: 'Completed Monthly Payroll Run',
    module: 'Payroll',
    details: 'Finalized and disbursed July 2026 Payroll Run for 9 employees',
    timestamp: '2026-07-31T17:00:00Z',
  },
  {
    id: 'log-3',
    userName: 'Elena Rostova',
    userRole: 'HR Manager',
    action: 'Submitted Performance Review',
    module: 'Performance',
    details: 'Submitted Q2 2026 Review for Michael Chang with rating 4.8/5.0',
    timestamp: '2026-07-05T11:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientId: 'EMP-1001',
    title: 'Pending Leave Approvals',
    message: '2 leave requests are waiting for approval from Michael Chang & Aisha Patel.',
    type: 'leave',
    read: false,
    createdAt: '2026-08-05T09:15:00Z',
  },
  {
    id: 'notif-2',
    recipientId: 'ALL',
    title: 'Upcoming Birthday',
    message: 'Michael Chang (Engineering) has a birthday coming up on Aug 9!',
    type: 'birthday',
    read: false,
    createdAt: '2026-08-05T08:00:00Z',
  },
  {
    id: 'notif-3',
    recipientId: 'ALL',
    title: 'Work Anniversary',
    message: 'Michael Chang celebrates 4 years at Etex Technologies on Aug 15!',
    type: 'system',
    read: true,
    createdAt: '2026-08-04T10:00:00Z',
  },
];
