import {
  Employee,
  Department,
  Position,
  AttendanceRecord,
  LeaveRequest,
  Payslip,
  PerformanceReview,
  JobOpening,
  Candidate,
  Asset,
  Announcement,
  AuditLog,
  CompanySettings,
  NotificationItem,
} from '../types';

export const INITIAL_SETTINGS: CompanySettings = {
  companyName: 'Etex Technologies Inc.',
  taxId: 'ET-984321092',
  currency: 'ETB',
  fiscalYearStart: '01-01',
  payFrequency: 'Monthly',
  standardWorkHours: 8,
  overtimeMultiplier: 1.5,
  annualLeaveDays: 20,
  sickLeaveDays: 10,
  maternityLeaveDays: 90,
  paternityLeaveDays: 14,
  address: 'Bole, Addis Ababa Ethiopia',
  contactEmail: 'hr@etex.com',
  contactPhone: '+1 (415) 890-2300',
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Engineering',
    code: 'ENG',
    managerId: 'EMP-1002',
    managerName: 'Eleni Moges',
    costCenter: 'CC-101',
    location: 'HQ - Addis Ababa',
    description: 'Product development, infrastructure, AI & software engineering.',
    employeeCount: 6,
  },
  {
    id: 'dept-2',
    name: 'Human Resources',
    code: 'HR',
    managerId: 'EMP-1001',
    managerName: 'Sara Belay',
    costCenter: 'CC-102',
    location: 'HQ - Addis Ababa',
    description: 'Talent acquisition, employee experience, compliance & payroll.',
    employeeCount: 3,
  },
  {
    id: 'dept-3',
    name: 'Sales & Marketing',
    code: 'SLM',
    managerId: 'EMP-1005',
    managerName: 'Hanna Yohannes',
    costCenter: 'CC-103',
    location: 'HQ - Addis Ababa',
    description: 'Enterprise business development, growth, and brand strategy.',
    employeeCount: 4,
  },
  {
    id: 'dept-4',
    name: 'Finance & Accounting',
    code: 'FIN',
    managerId: 'EMP-1008',
    managerName: 'Yonas Girma',
    costCenter: 'CC-104',
    location: 'HQ - Addis Ababa',
    description: 'Financial planning, reporting, treasury, and audit.',
    employeeCount: 2,
  },
  {
    id: 'dept-5',
    name: 'Product & Design',
    code: 'PRD',
    managerId: 'EMP-1003',
    managerName: 'Tewodros Assefa',
    costCenter: 'CC-105',
    location: 'HQ - Addis Ababa',
    description: 'User experience research, UI design, and product lifecycle management.',
    employeeCount: 3,
  },
];

export const INITIAL_POSITIONS: Position[] = [
  { id: 'pos-1', title: 'VP of Engineering', department: 'Engineering', grade: 'E-8', description: 'Leads global engineering team and technology strategy.' },
  { id: 'pos-2', title: 'Senior Software Engineer', department: 'Engineering', grade: 'E-5', description: 'Full-stack application development & cloud architecture.' },
  { id: 'pos-3', title: 'Frontend Developer', department: 'Engineering', grade: 'E-3', description: 'UI component development and performance optimization.' },
  { id: 'pos-4', title: 'HR Director', department: 'Human Resources', grade: 'M-7', description: 'Strategic HR, policy governance, and organizational development.' },
  { id: 'pos-5', title: 'Payroll & Benefits Specialist', department: 'Human Resources', grade: 'M-4', description: 'Monthly payroll calculation, tax filings, and benefits admin.' },
  { id: 'pos-6', title: 'Lead Product Designer', department: 'Product & Design', grade: 'P-5', description: 'Design system architecture and user experience strategy.' },
  { id: 'pos-7', title: 'Sales Manager', department: 'Sales & Marketing', grade: 'S-6', description: 'Enterprise sales pipeline management and client revenue.' },
  { id: 'pos-8', title: 'Senior Financial Analyst', department: 'Finance & Accounting', grade: 'F-5', description: 'FP&A modeling, budget forecasting, and cost audit.' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1001',
    employeeId: 'EMP-1001',
    firstName: 'Sara',
    lastName: 'Belay',
    fullName: 'Sara Belay',
    email: 'sara.belay@etex.com',
    phone: '+251 91 123 4567',
    gender: 'Female',
    dateOfBirth: '1988-08-14',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    address: 'Bole Sub-City, Woreda 03, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Tewodros Belay', relationship: 'Spouse', phone: '+251 91 198 7654' },
    department: 'Human Resources',
    position: 'HR Director',
    employmentType: 'Full-Time',
    hireDate: '2021-03-15',
    employmentStatus: 'Active',
    salary: 65000,
    payType: 'Salary',
    hourlyRate: 375,
    payFrequency: 'Monthly',
    costCenter: 'CC-102',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Commercial Bank of Ethiopia', accountNumber: '****4829', routingNumber: 'CBE-001' },
    taxInfo: { taxId: 'ET-TIN-4819', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [
      { id: 'doc-1', name: 'Offer_Letter_Belay.pdf', type: 'Offer Letter', url: '#', uploadedAt: '2021-03-01' },
      { id: 'doc-2', name: 'Employment_Contract_2021.pdf', type: 'Contract', url: '#', uploadedAt: '2021-03-15' },
    ],
    leaveBalance: { annual: 18, sick: 9, personal: 4, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Primary HR Admin contact.',
    createdAt: '2021-03-15T09:00:00Z',
    updatedAt: '2026-08-01T10:30:00Z',
  },
  {
    id: 'emp-1002',
    employeeId: 'EMP-1002',
    firstName: 'Eleni',
    lastName: 'Moges',
    fullName: 'Eleni Moges',
    email: 'eleni.moges@etex.com',
    phone: '+251 91 234 5678',
    gender: 'Female',
    dateOfBirth: '1985-11-22',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    address: 'Kirkos Sub-City, Kazanchis, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Kibrom Moges', relationship: 'Brother', phone: '+251 91 287 6543' },
    department: 'Engineering',
    position: 'VP of Engineering',
    employmentType: 'Full-Time',
    hireDate: '2020-01-10',
    employmentStatus: 'Active',
    salary: 95000,
    payType: 'Salary',
    hourlyRate: 548,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Dashen Bank', accountNumber: '****9102', routingNumber: 'DASH-002' },
    taxInfo: { taxId: 'ET-TIN-9012', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [
      { id: 'doc-3', name: 'Contract_Moges.pdf', type: 'Contract', url: '#', uploadedAt: '2020-01-10' },
    ],
    leaveBalance: { annual: 14, sick: 10, personal: 5, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Department manager for Engineering.',
    createdAt: '2020-01-10T09:00:00Z',
    updatedAt: '2026-08-01T11:00:00Z',
  },
  {
    id: 'emp-1003',
    employeeId: 'EMP-1003',
    firstName: 'Tewodros',
    lastName: 'Assefa',
    fullName: 'Tewodros Assefa',
    email: 'tewodros.assefa@etex.com',
    phone: '+251 91 345 6789',
    gender: 'Male',
    dateOfBirth: '1992-04-18',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    address: 'Yeka Sub-City, Megenagna, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Meseret Assefa', relationship: 'Sister', phone: '+251 91 376 5432' },
    department: 'Product & Design',
    position: 'Lead Product Designer',
    managerId: 'EMP-1002',
    managerName: 'Eleni Moges',
    employmentType: 'Full-Time',
    hireDate: '2022-06-01',
    employmentStatus: 'Active',
    salary: 55000,
    payType: 'Salary',
    hourlyRate: 317,
    payFrequency: 'Monthly',
    costCenter: 'CC-105',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Bank of Abyssinia', accountNumber: '****3391', routingNumber: 'BOA-003' },
    taxInfo: { taxId: 'ET-TIN-3301', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [
      { id: 'doc-4', name: 'Resume_Assefa.pdf', type: 'Resume', url: '#', uploadedAt: '2022-05-15' },
    ],
    leaveBalance: { annual: 12, sick: 8, personal: 3, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Leads UI/UX design chapter.',
    createdAt: '2022-06-01T09:00:00Z',
    updatedAt: '2026-08-01T11:15:00Z',
  },
  {
    id: 'emp-1004',
    employeeId: 'EMP-1004',
    firstName: 'Dawit',
    lastName: 'Tadesse',
    fullName: 'Dawit Tadesse',
    email: 'dawit.tadesse@etex.com',
    phone: '+251 91 456 7890',
    gender: 'Male',
    dateOfBirth: '1995-08-09',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    address: 'Nifas Silk-Lafto, Sarbet, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Almaz Tadesse', relationship: 'Mother', phone: '+251 91 465 4321' },
    department: 'Engineering',
    position: 'Senior Software Engineer',
    managerId: 'EMP-1002',
    managerName: 'Eleni Moges',
    employmentType: 'Full-Time',
    hireDate: '2022-08-15',
    employmentStatus: 'Active',
    salary: 60000,
    payType: 'Salary',
    hourlyRate: 346,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Awash Bank', accountNumber: '****7712', routingNumber: 'AWASH-004' },
    taxInfo: { taxId: 'ET-TIN-7811', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 15, sick: 10, personal: 4, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Core contributor on backend infrastructure.',
    createdAt: '2022-08-15T09:00:00Z',
    updatedAt: '2026-08-01T11:20:00Z',
  },
  {
    id: 'emp-1005',
    employeeId: 'EMP-1005',
    firstName: 'Hanna',
    lastName: 'Yohannes',
    fullName: 'Hanna Yohannes',
    email: 'hanna.yohannes@etex.com',
    phone: '+251 91 567 8901',
    gender: 'Female',
    dateOfBirth: '1987-12-03',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    address: 'Bole Sub-City, Atlas, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Yohannes Tekle', relationship: 'Father', phone: '+251 91 554 3210' },
    department: 'Sales & Marketing',
    position: 'Sales Manager',
    employmentType: 'Full-Time',
    hireDate: '2021-09-01',
    employmentStatus: 'Active',
    salary: 50000,
    payType: 'Salary',
    hourlyRate: 288,
    payFrequency: 'Monthly',
    costCenter: 'CC-103',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Hibret Bank', accountNumber: '****1182', routingNumber: 'HIB-005' },
    taxInfo: { taxId: 'ET-TIN-1102', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 16, sick: 7, personal: 2, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Head of Enterprise Sales & Growth.',
    createdAt: '2021-09-01T09:00:00Z',
    updatedAt: '2026-08-01T11:30:00Z',
  },
  {
    id: 'emp-1006',
    employeeId: 'EMP-1006',
    firstName: 'Selamawit',
    lastName: 'Alemu',
    fullName: 'Selamawit Alemu',
    email: 'selamawit.alemu@etex.com',
    phone: '+251 91 678 9012',
    gender: 'Female',
    dateOfBirth: '1996-08-28',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    address: 'Arada Sub-City, Piassa, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Alemu Worku', relationship: 'Father', phone: '+251 91 643 2109' },
    department: 'Engineering',
    position: 'Frontend Developer',
    managerId: 'EMP-1002',
    managerName: 'Eleni Moges',
    employmentType: 'Full-Time',
    hireDate: '2024-02-01',
    employmentStatus: 'Active',
    salary: 42000,
    payType: 'Salary',
    hourlyRate: 242,
    payFrequency: 'Monthly',
    costCenter: 'CC-101',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Cooperative Bank of Oromia', accountNumber: '****9012', routingNumber: 'CBO-006' },
    taxInfo: { taxId: 'ET-TIN-5521', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 19, sick: 10, personal: 5, maternity: 90, paternity: 0, bereavement: 5 },
    notes: 'Specializes in React & Tailwind Web Applications.',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2026-08-01T11:40:00Z',
  },
  {
    id: 'emp-1007',
    employeeId: 'EMP-1007',
    firstName: 'Abebe',
    lastName: 'Bikila',
    fullName: 'Abebe Bikila',
    email: 'abebe.bikila@etex.com',
    phone: '+251 91 789 0123',
    gender: 'Male',
    dateOfBirth: '1991-03-14',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    address: 'Gullele Sub-City, Shiro Meda, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Tirunesh Bikila', relationship: 'Spouse', phone: '+251 91 732 1098' },
    department: 'Human Resources',
    position: 'Payroll & Benefits Specialist',
    managerId: 'EMP-1001',
    managerName: 'Sara Belay',
    employmentType: 'Full-Time',
    hireDate: '2023-05-10',
    employmentStatus: 'Active',
    salary: 38000,
    payType: 'Salary',
    hourlyRate: 219,
    payFrequency: 'Monthly',
    costCenter: 'CC-102',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Commercial Bank of Ethiopia', accountNumber: '****4402', routingNumber: 'CBE-001' },
    taxInfo: { taxId: 'ET-TIN-4491', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 16, sick: 8, personal: 3, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Payroll Officer role user.',
    createdAt: '2023-05-10T09:00:00Z',
    updatedAt: '2026-08-01T11:45:00Z',
  },
  {
    id: 'emp-1008',
    employeeId: 'EMP-1008',
    firstName: 'Yonas',
    lastName: 'Girma',
    fullName: 'Yonas Girma',
    email: 'yonas.girma@etex.com',
    phone: '+251 91 890 1234',
    gender: 'Male',
    dateOfBirth: '1984-07-30',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    address: 'Lideta Sub-City, Mexico, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Genet Girma', relationship: 'Spouse', phone: '+251 91 821 0987' },
    department: 'Finance & Accounting',
    position: 'Senior Financial Analyst',
    employmentType: 'Full-Time',
    hireDate: '2020-08-10',
    employmentStatus: 'Active',
    salary: 58000,
    payType: 'Salary',
    hourlyRate: 335,
    payFrequency: 'Monthly',
    costCenter: 'CC-104',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Zemen Bank', accountNumber: '****8831', routingNumber: 'ZEM-007' },
    taxInfo: { taxId: 'ET-TIN-8822', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 15, sick: 9, personal: 4, maternity: 0, paternity: 14, bereavement: 5 },
    notes: 'Finance department manager.',
    createdAt: '2020-08-10T09:00:00Z',
    updatedAt: '2026-08-01T11:50:00Z',
  },
  {
    id: 'emp-1009',
    employeeId: 'EMP-1009',
    firstName: 'Bethelhem',
    lastName: 'Haile',
    fullName: 'Bethelhem Haile',
    email: 'bethelhem.haile@etex.com',
    phone: '+251 91 901 2345',
    gender: 'Female',
    dateOfBirth: '1994-10-12',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    address: 'Akaki Kality, Kaliti, Addis Ababa, Ethiopia',
    emergencyContact: { name: 'Haile Mariam', relationship: 'Father', phone: '+251 91 910 9876' },
    department: 'Sales & Marketing',
    position: 'Marketing Specialist',
    managerId: 'EMP-1005',
    managerName: 'Hanna Yohannes',
    employmentType: 'Full-Time',
    hireDate: '2023-11-01',
    employmentStatus: 'On Leave',
    salary: 35000,
    payType: 'Salary',
    hourlyRate: 201,
    payFrequency: 'Monthly',
    costCenter: 'CC-103',
    location: 'HQ - Addis Ababa',
    bankInfo: { bankName: 'Commercial Bank of Ethiopia', accountNumber: '****5521', routingNumber: 'CBE-001' },
    taxInfo: { taxId: 'ET-TIN-9901', filingStatus: 'Single', allowances: 0 },
    workSchedule: 'Mon - Fri, 8:30 AM - 5:00 PM',
    documents: [],
    leaveBalance: { annual: 10, sick: 6, personal: 2, maternity: 80, paternity: 0, bereavement: 5 },
    notes: 'Currently on Maternity leave.',
    createdAt: '2023-11-01T09:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'EMP-1001',
    employeeName: 'Sara Belay',
    department: 'Human Resources',
    date: '2026-08-05',
    clockIn: '08:52 AM',
    clockOut: '05:05 PM',
    breakDurationMinutes: 45,
    totalHours: 7.5,
    overtimeHours: 0,
    status: 'Present',
  },
  {
    id: 'att-2',
    employeeId: 'EMP-1002',
    employeeName: 'Eleni Moges',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:45 AM',
    clockOut: '05:30 PM',
    breakDurationMinutes: 60,
    totalHours: 7.75,
    overtimeHours: 0.5,
    status: 'Present',
  },
  {
    id: 'att-3',
    employeeId: 'EMP-1003',
    employeeName: 'Tewodros Assefa',
    department: 'Product & Design',
    date: '2026-08-05',
    clockIn: '09:18 AM',
    clockOut: '05:00 PM',
    breakDurationMinutes: 60,
    totalHours: 6.7,
    overtimeHours: 0,
    status: 'Late',
    notes: 'Traffic delay around Megenagna Square',
  },
  {
    id: 'att-4',
    employeeId: 'EMP-1004',
    employeeName: 'Dawit Tadesse',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:55 AM',
    clockOut: '06:15 PM',
    breakDurationMinutes: 45,
    totalHours: 8.5,
    overtimeHours: 1.25,
    status: 'Present',
  },
  {
    id: 'att-5',
    employeeId: 'EMP-1006',
    employeeName: 'Selamawit Alemu',
    department: 'Engineering',
    date: '2026-08-05',
    clockIn: '08:50 AM',
    clockOut: '05:00 PM',
    breakDurationMinutes: 60,
    totalHours: 7.1,
    overtimeHours: 0,
    status: 'Present',
  },
  {
    id: 'att-6',
    employeeId: 'EMP-1009',
    employeeName: 'Bethelhem Haile',
    department: 'Sales & Marketing',
    date: '2026-08-05',
    breakDurationMinutes: 0,
    totalHours: 0,
    overtimeHours: 0,
    status: 'On Leave',
    notes: 'Approved Maternity Leave',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lv-101',
    employeeId: 'EMP-1004',
    employeeName: 'Dawit Tadesse',
    department: 'Engineering',
    leaveType: 'Annual',
    startDate: '2026-08-18',
    endDate: '2026-08-22',
    totalDays: 5,
    reason: 'Family vacation trip.',
    status: 'Pending',
    appliedAt: '2026-08-04T14:20:00Z',
  },
  {
    id: 'lv-102',
    employeeId: 'EMP-1006',
    employeeName: 'Selamawit Alemu',
    department: 'Engineering',
    leaveType: 'Sick',
    startDate: '2026-08-10',
    endDate: '2026-08-11',
    totalDays: 2,
    reason: 'Medical treatment and rest.',
    status: 'Pending',
    appliedAt: '2026-08-05T09:10:00Z',
  },
  {
    id: 'lv-103',
    employeeId: 'EMP-1003',
    employeeName: 'Tewodros Assefa',
    department: 'Product & Design',
    leaveType: 'Personal',
    startDate: '2026-07-28',
    endDate: '2026-07-29',
    totalDays: 2,
    reason: 'Family event in Bishoftu.',
    status: 'Approved',
    approverId: 'EMP-1002',
    approverName: 'Eleni Moges',
    approverNote: 'Approved. Safe travels!',
    appliedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'lv-104',
    employeeId: 'EMP-1009',
    employeeName: 'Bethelhem Haile',
    department: 'Sales & Marketing',
    leaveType: 'Maternity',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    totalDays: 65,
    reason: 'Maternity leave.',
    status: 'Approved',
    approverId: 'EMP-1001',
    approverName: 'Sara Belay',
    approverNote: 'Congratulations on your new baby!',
    appliedAt: '2026-06-15T11:00:00Z',
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-2026-08-1001',
    payrollRunId: 'pr-2026-08',
    employeeId: 'EMP-1001',
    employeeName: 'Sara Belay',
    employeeEmail: 'sara.belay@etex.com',
    department: 'Human Resources',
    position: 'HR Director',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    payDate: '2026-08-31',
    frequency: 'Monthly',
    baseSalary: 65000.00,
    hourlyRate: 375,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 5000,
    commissions: 0,
    allowances: 3000,
    grossPay: 73000.00,
    taxDeductions: 18500.00,
    retirementDeductions: 4550.00,
    otherDeductions: 500.00,
    totalDeductions: 23550.00,
    netPay: 49450.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Commercial Bank of Ethiopia',
    accountNumber: '****4829',
    status: 'Completed',
  },
  {
    id: 'ps-2026-08-1002',
    payrollRunId: 'pr-2026-08',
    employeeId: 'EMP-1002',
    employeeName: 'Eleni Moges',
    employeeEmail: 'eleni.moges@etex.com',
    department: 'Engineering',
    position: 'VP of Engineering',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    payDate: '2026-08-31',
    frequency: 'Monthly',
    baseSalary: 95000.00,
    hourlyRate: 548,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 10000,
    commissions: 0,
    allowances: 4000,
    grossPay: 109000.00,
    taxDeductions: 31000.00,
    retirementDeductions: 6650.00,
    otherDeductions: 1000.00,
    totalDeductions: 38650.00,
    netPay: 70350.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Dashen Bank',
    accountNumber: '****9102',
    status: 'Completed',
  },
  {
    id: 'ps-2026-08-1004',
    payrollRunId: 'pr-2026-08',
    employeeId: 'EMP-1004',
    employeeName: 'Dawit Tadesse',
    employeeEmail: 'dawit.tadesse@etex.com',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    payDate: '2026-08-31',
    frequency: 'Monthly',
    baseSalary: 60000.00,
    hourlyRate: 346,
    hoursWorked: 168,
    overtimePay: 4152.00,
    bonuses: 3000,
    commissions: 0,
    allowances: 2000,
    grossPay: 69152.00,
    taxDeductions: 17200.00,
    retirementDeductions: 4200.00,
    otherDeductions: 500.00,
    totalDeductions: 21900.00,
    netPay: 47252.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Awash Bank',
    accountNumber: '****7712',
    status: 'Completed',
  },
  {
    id: 'ps-2026-07-1001',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1001',
    employeeName: 'Sara Belay',
    employeeEmail: 'sara.belay@etex.com',
    department: 'Human Resources',
    position: 'HR Director',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 65000.00,
    hourlyRate: 375,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 5000,
    commissions: 0,
    allowances: 3000,
    grossPay: 73000.00,
    taxDeductions: 18500.00,
    retirementDeductions: 4550.00,
    otherDeductions: 500.00,
    totalDeductions: 23550.00,
    netPay: 49450.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Commercial Bank of Ethiopia',
    accountNumber: '****4829',
    status: 'Completed',
  },
  {
    id: 'ps-2026-07-1002',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1002',
    employeeName: 'Eleni Moges',
    employeeEmail: 'eleni.moges@etex.com',
    department: 'Engineering',
    position: 'VP of Engineering',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 95000.00,
    hourlyRate: 548,
    hoursWorked: 160,
    overtimePay: 0,
    bonuses: 10000,
    commissions: 0,
    allowances: 4000,
    grossPay: 109000.00,
    taxDeductions: 31000.00,
    retirementDeductions: 6650.00,
    otherDeductions: 1000.00,
    totalDeductions: 38650.00,
    netPay: 70350.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Dashen Bank',
    accountNumber: '****9102',
    status: 'Completed',
  },
  {
    id: 'ps-2026-07-1004',
    payrollRunId: 'pr-2026-07',
    employeeId: 'EMP-1004',
    employeeName: 'Dawit Tadesse',
    employeeEmail: 'dawit.tadesse@etex.com',
    department: 'Engineering',
    position: 'Senior Software Engineer',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    payDate: '2026-07-31',
    frequency: 'Monthly',
    baseSalary: 60000.00,
    hourlyRate: 346,
    hoursWorked: 168,
    overtimePay: 4152.00,
    bonuses: 3000,
    commissions: 0,
    allowances: 2000,
    grossPay: 69152.00,
    taxDeductions: 17200.00,
    retirementDeductions: 4200.00,
    otherDeductions: 500.00,
    totalDeductions: 21900.00,
    netPay: 47252.00,
    paymentMethod: 'Direct Deposit',
    bankName: 'Awash Bank',
    accountNumber: '****7712',
    status: 'Completed',
  },
];

export const INITIAL_PERFORMANCE_REVIEWS: PerformanceReview[] = [
  {
    id: 'rev-1',
    employeeId: 'EMP-1004',
    employeeName: 'Dawit Tadesse',
    reviewerId: 'EMP-1002',
    reviewerName: 'Eleni Moges',
    reviewPeriod: 'Q2 2026',
    overallRating: 4.8,
    goals: [
      { id: 'g1', title: 'Migrate legacy services', description: 'Complete backend migration with zero downtime.', status: 'Completed', progress: 100, dueDate: '2026-06-30' },
      { id: 'g2', title: 'Improve test coverage to 85%', description: 'Write unit & integration tests.', status: 'In Progress', progress: 75, dueDate: '2026-09-30' },
    ],
    feedback: 'Dawit has demonstrated stellar technical leadership and architectural excellence during the infrastructure upgrade.',
    strengths: 'System design, reliability, team mentoring',
    improvements: 'Technical documentation completeness',
    status: 'Completed',
    reviewDate: '2026-07-05',
  },
  {
    id: 'rev-2',
    employeeId: 'EMP-1006',
    employeeName: 'Selamawit Alemu',
    reviewerId: 'EMP-1002',
    reviewerName: 'Eleni Moges',
    reviewPeriod: 'Q2 2026',
    overallRating: 4.5,
    goals: [
      { id: 'g3', title: 'Redesign UI System Components', description: 'Build accessible Tailwind UI primitives.', status: 'Completed', progress: 100, dueDate: '2026-06-30' },
    ],
    feedback: 'Selamawit delivered exceptional UI components and significantly boosted web application responsiveness.',
    strengths: 'UI Craftsmanship, fast execution, accessibility focus',
    improvements: 'Cross-browser testing protocols',
    status: 'Completed',
    reviewDate: '2026-07-08',
  },
];

export const INITIAL_JOBS: JobOpening[] = [
  {
    id: 'job-1',
    title: 'Senior DevOps / Site Reliability Engineer',
    department: 'Engineering',
    location: 'HQ - Addis Ababa',
    employmentType: 'Full-Time',
    status: 'Open',
    salaryRange: 'ETB 60,000 - 85,000 / mo',
    applicantsCount: 14,
    description: 'Lead cloud infrastructure orchestration, Terraform IaC, and CI/CD pipelines.',
    requirements: ['5+ years DevOps/SRE', 'Cloud infrastructure, Docker, Kubernetes', 'CI/CD & Monitoring'],
    postedDate: '2026-07-15',
  },
  {
    id: 'job-2',
    title: 'Senior Product Manager',
    department: 'Product & Design',
    location: 'HQ - Addis Ababa',
    employmentType: 'Full-Time',
    status: 'Open',
    salaryRange: 'ETB 50,000 - 75,000 / mo',
    applicantsCount: 9,
    description: 'Drive product roadmap for HRMS enterprise features and integrations.',
    requirements: ['4+ years B2B SaaS PM', 'Data analytics & user research', 'Agile leadership'],
    postedDate: '2026-07-20',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    jobId: 'job-1',
    jobTitle: 'Senior DevOps / Site Reliability Engineer',
    name: 'Getachew Assefa',
    email: 'getachew.assefa@gmail.com',
    phone: '+251 91 112 2334',
    status: 'Interview',
    appliedDate: '2026-07-18',
    interviewDate: '2026-08-08 at 2:00 PM',
    notes: 'Passed initial screening call with flying colors. Strong cloud expertise.',
    rating: 4,
  },
  {
    id: 'cand-2',
    jobId: 'job-1',
    jobTitle: 'Senior DevOps / Site Reliability Engineer',
    name: 'Mahlet Solomon',
    email: 'mahlet.solomon@techmail.com',
    phone: '+251 91 223 3445',
    status: 'Screening',
    appliedDate: '2026-07-22',
    notes: 'Resume looks solid. Strong cloud background.',
    rating: 5,
  },
  {
    id: 'cand-3',
    jobId: 'job-2',
    jobTitle: 'Senior Product Manager',
    name: 'Kassahun Worku',
    email: 'kassahun.worku@innovate.et',
    phone: '+251 91 334 4556',
    status: 'Offer',
    appliedDate: '2026-07-21',
    notes: 'Final round interview completed. Extended offer letter.',
    rating: 5,
  },
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-1',
    assetTag: 'AST-MBP-101',
    name: 'MacBook Pro 16" M3 Max (32GB / 1TB)',
    category: 'Laptop',
    serialNumber: 'C02G8091Q05P',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1004',
    assignedEmployeeName: 'Dawit Tadesse',
    assignedDate: '2022-08-15',
    value: 180000,
    notes: 'High performance engineer laptop',
  },
  {
    id: 'ast-2',
    assetTag: 'AST-MON-204',
    name: 'Dell UltraSharp 32" 4K USB-C Monitor',
    category: 'Monitor',
    serialNumber: 'CN-09121-770',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1003',
    assignedEmployeeName: 'Tewodros Assefa',
    assignedDate: '2022-06-05',
    value: 45000,
    notes: 'Color calibrated for product design team',
  },
  {
    id: 'ast-3',
    assetTag: 'AST-MBP-102',
    name: 'MacBook Air 15" M3 (16GB / 512GB)',
    category: 'Laptop',
    serialNumber: 'C02H1108P901',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1001',
    assignedEmployeeName: 'Sara Belay',
    assignedDate: '2023-01-10',
    value: 95000,
  },
  {
    id: 'ast-4',
    assetTag: 'AST-ACC-001',
    name: 'HQ Master Keycard & Parking Pass #042',
    category: 'Access Card',
    serialNumber: 'KEY-ADD-042',
    status: 'Assigned',
    assignedEmployeeId: 'EMP-1002',
    assignedEmployeeName: 'Eleni Moges',
    assignedDate: '2020-01-10',
    value: 2500,
  },
  {
    id: 'ast-5',
    assetTag: 'AST-MBP-105',
    name: 'MacBook Pro 14" M3 Pro (18GB / 512GB)',
    category: 'Laptop',
    serialNumber: 'C02F9918A003',
    status: 'Available',
    value: 110000,
    notes: 'Ready for next new hire in Engineering',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Q3 Town Hall & All-Hands Meeting',
    content: 'Join us this Thursday at 10:00 AM for our Q3 Company Update. We will share financial performance, product milestones, and welcome new team members.',
    author: 'Sara Belay (HR)',
    category: 'Event',
    isPinned: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'anc-2',
    title: 'Updated Health & Benefits Package for 2026',
    content: 'We are excited to introduce enhanced healthcare coverage including outpatient consultation support and wellness stipends.',
    author: 'Abebe Bikila (Payroll)',
    category: 'Policy',
    isPinned: false,
    createdAt: '2026-07-25T14:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userName: 'Sara Belay',
    userRole: 'HR Manager',
    action: 'Approved Leave Request',
    module: 'Leave Management',
    details: 'Approved 2 days personal leave for Tewodros Assefa (EMP-1003)',
    timestamp: '2026-08-04T16:10:00Z',
  },
  {
    id: 'log-2',
    userName: 'Abebe Bikila',
    userRole: 'HR Manager',
    action: 'Completed Monthly Payroll Run',
    module: 'Payroll',
    details: 'Finalized and disbursed July 2026 Payroll Run for 9 employees',
    timestamp: '2026-07-31T17:00:00Z',
  },
  {
    id: 'log-3',
    userName: 'Eleni Moges',
    userRole: 'HR Manager',
    action: 'Submitted Performance Review',
    module: 'Performance',
    details: 'Submitted Q2 2026 Review for Dawit Tadesse with rating 4.8/5.0',
    timestamp: '2026-07-05T11:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientId: 'EMP-1001',
    title: 'Pending Leave Approvals',
    message: '2 leave requests are waiting for approval from Dawit Tadesse & Selamawit Alemu.',
    type: 'leave',
    read: false,
    createdAt: '2026-08-05T09:15:00Z',
  },
  {
    id: 'notif-2',
    recipientId: 'ALL',
    title: 'Upcoming Birthday',
    message: 'Dawit Tadesse (Engineering) has a birthday coming up on Aug 9!',
    type: 'birthday',
    read: false,
    createdAt: '2026-08-05T08:00:00Z',
  },
  {
    id: 'notif-3',
    recipientId: 'ALL',
    title: 'Work Anniversary',
    message: 'Dawit Tadesse celebrates 4 years at Etex Technologies on Aug 15!',
    type: 'system',
    read: true,
    createdAt: '2026-08-04T10:00:00Z',
  },
];
